    - name: {{ type }}{{num}}
      {{ type }}:
        {% if type=="junos_command" %}
        {{ args }}
        {% else %}
        {{ args }}
        {% endif %}
      register: {{ type }}{{ num }}response
    - name: output {{ type }}{{ num }}
      debug:
        var: {{ type }}{{ num }}response.stdout_lines {{"\n"}}
