---
- hosts: {{host}}
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: {{ name }}
      {{ commType }}:
      {% if name == "generic" %}
        commands: {{args}}
      {% else %}
        {% for arg in args %}
        {{arg}}
        {% endfor %}
      {% endif %}

      register: response

    - name: debug
      debug:
        var: response.stdout_lines